backend/uBLOG/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

urlpatterns = [
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>/', views.UserDetail.as_view()),
    path('blogs/', views.BlogList.as_view()),
    path('blogs/<int:pk>/', views.BlogDetail.as_view()),
    path('comments/', views.CommentList.as_view()),
    path('comments/<int:pk>/', views.CommentDetail.as_view()),
    path('categories/', views.CategoryList.as_view()),
    path('categories/<int:pk>/', views.CategoryDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

backend/uBLOG/blogs/urls.py
from django.urls import path
from. import views

app_name = 'blogs'

urlpatterns = [
    path('', views.blogs, name='blogs'),
    path('create/', views.create_blog, name='create'),
    path('update/<slug>/', views.update_blog, name='update'),
    path('delete/<slug>/', views.delete_blog, name='delete'),
    path('<slug>', views.blog, name='blog'),
]

backend/uBLOG/uBLOG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from. import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('api-path/', include('rest_framework.urls')),
    path('', views.homepage, name='homepage'),
    path('accounts/', include('accounts.urls')),
    path('blogs/', include('blogs.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/uBLOG/blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100, blank=False, unique=True)
    slug = models.SlugField()
    body = models.TextField(blank=False)
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.body[:30] + '...'

backend/uBLOG/blogs/forms.py
from django import forms
from . import models

class CreateBlog(forms.ModelForm):
    class Meta:
        model = models.Blog
        fields = ['title', 'slug', 'body', 'thumb']
        
class UpdateBlog(forms.ModelForm):
    class Meta:
        model = models.Blog
        fields = ['title', 'slug', 'body', 'thumb']

backend/uBLOG/blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from . import forms
from .models import Blog

# Create your views here.
def blogs(request):
    blogs = Blog.objects.all().order_by('date')
    return render(request, 'blogs/blogs.html', { 'blogs': blogs })

def blog(request, slug):
    blog = Blog.objects.get(slug=slug)
    return render(request, 'blogs/blog.html', { 'blog': blog })
    # try:
    #     blogs = Blog.objects.all().order_by('date')
    #     for blog in blogs:
    #         if blog.author.username == author and blog.slug == slug: 
    #             return render(request, 'blogs/blog.html', { 'blog': blog })
    # except:
        # return redirect('blogs:blogs')

    

@login_required(login_url="/accounts/login/")
def create_blog(request):
    if request.method == 'POST':
        form = forms.CreateBlog(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('blogs:blogs')
    else:
        form = forms.CreateBlog()
    return render(request, 'blogs/create.html', { 'form': form })

@login_required(login_url="/accounts/login/")
def update_blog(request, slug):
    blog = Blog.objects.get(slug=slug)
    if request.method == 'POST':
        form = forms.UpdateBlog(request.POST, request.FILES, instance=blog)
        if form.is_valid():
            form.save()
            return redirect('blogs:blogs')
    else:
        form = forms.UpdateBlog(instance=blog)
        print(blog.author)
    return render(request, 'blogs/update.html', {'blog': blog ,'form': form})

@login_required(login_url="/accounts/login/")
def delete_blog(request, slug):
    blog = Blog.objects.get(slug=slug)
    print(request)
    if request.method == 'GET':
        blog.delete()
        return redirect('blogs:blogs')

backend/uBLOG/blogs/templates/blogs/blog.html
{% extends 'base.html' %}

{% block content %}
    <div class="blog-details">
        <div class="blog">
            <img src="{{ blog.thumb.url }}" alt="{{ blog.slug }}">
            <h2>
                <div>
                    <div class="blog-details-title">
                        {{ blog.title }}
                    </div> 
                    <div class="blog-details-author">
                        {{ blog.author }} - {{ blog.date }}
                    </div>
                </div>
                
                
            </h2>
            <p>{{ blog.body }}</p>
          

            {% if user.is_authenticated and user == blog.author %}
                    <a href="{% url 'blogs:update' slug=blog.slug %}" class="highlight">Update</a>
                    <a href="{% url 'blogs:delete' slug=blog.slug %}" class="highlight">Delete</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

backend/uBLOG/blogs/templates/blogs/blogs.html
{% extends 'base.html' %}

{% block content %}
    <h1 style="font-weight: bold;color:white">Blogs</h1>
    {% if user.is_authenticated and user != blog.author %}
        <div>Your Blogs</div>
        <div class="blogs">
            {% for blog in blogs %}
                {% if user.is_authenticated and user == blog.author %}
                <div>
                    <div class="blog-date">
                        {{ blog.date }}
                    </div>
                        <div class="blog">
                            <a href="{% url 'blogs:blog' slug=blog.slug %}">
                                <h2>{{ blog.title }}</h2>
                            </a>
                            <div class="blog-content">
                                {{ blog.snippet }}
                            </div>
                            
                            
                            <div  class="author">
                                <div class="author-text">
                                    
                                    <div>
                                        Author 
                                    </div> 
                                    
                                </div>
                                
                                <div class="author-text-author"> {{ blog.author }} </div>
                            </div>
                            
                        </div>
                </div>
                {% endif %}
            
            {% endfor %}
        </div>
        <div>Other's Blogs</div>
        <div class="blogs">
            {% for blog in blogs %}
                {% if user.is_authenticated and user != blog.author %}
                <div>
                    <div class="blog-date">
                        {{ blog.date }}
                    </div>
                        <div class="blog">
                            <a href="{% url 'blogs:blog' slug=blog.slug %}">
                                <h2>{{ blog.title }}</h2>
                            </a>
                            <div class="blog-content">
                                {{ blog.snippet }}
                            </div>
                            
                            
                            <div  class="author">
                                <div class="author-text">
                                    
                                    <div>
                                        Author 
                                    </div> 
                                    
                                </div>
                                
                                <div class="author-text-author"> {{ blog.author }} </div>
                            </div>
                            
                        </div>
                </div>
                {% endif %}
            
            {% endfor %}
        </div>
    {% endif %}
    {% if not user.is_authenticated %}
        <div class="blogs">
            {% for blog in blogs %}
            
                <div>
                    <div class="blog-date">
                        {{ blog.date }}
                    </div>
                        <div class="blog">
                            <a href="{% url 'blogs:blog' slug=blog.slug %}">
                                <h2>{{ blog.title }}</h2>
                            </a>
                            <div class="blog-content">
                                {{ blog.snippet }}
                            </div>
                            
                            
                            <div  class="author">
                                <div class="author-text">
                                    
                                    <div>
                                        Author 
                                    </div> 
                                    
                                </div>
                                
                                <div class="author-text-author"> {{ blog.author }} </div>
                            </div>
                            
                        </div>
                </div>
            
            {% endfor %}
        </div>
    {% endif %}
    
{% endblock %}

backend/uBLOG/blogs/templates/blogs/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="create-blog">
        <h1>Create a Blog</h1>
        <form action="{% url 'blogs:create' %}" class="site-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

backend/uBLOG/blogs/templates/blogs/update.html
{% extends 'base.html' %}
{% block content %}
    <div class="update-blog">
        <h1>Update a Blog</h1>
        <form action="{% url 'blogs:update' slug=blog.slug %}" class="site-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Update">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}