backend/uBLOG/accounts/urls.py
from django.urls import path
from. import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

backend/uBLOG/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

urlpatterns = [
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>/', views.UserDetail.as_view()),
    path('blogs/', views.BlogList.as_view()),
    path('blogs/<int:pk>/', views.BlogDetail.as_view()),
    path('comments/', views.CommentList.as_view()),
    path('comments/<int:pk>/', views.CommentDetail.as_view()),
    path('categories/', views.CategoryList.as_view()),
    path('categories/<int:pk>/', views.CategoryDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

backend/uBLOG/blogs/urls.py
from django.urls import path
from. import views

app_name = 'blogs'

urlpatterns = [
    path('', views.blogs, name='blogs'),
    path('create/', views.create_blog, name='create'),
    path('update/<slug>/', views.update_blog, name='update'),
    path('delete/<slug>/', views.delete_blog, name='delete'),
    path('<slug>', views.blog, name='blog'),
]

backend/uBLOG/uBLOG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from. import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('api-path/', include('rest_framework.urls')),
    path('', views.homepage, name='homepage'),
    path('accounts/', include('accounts.urls')),
    path('blogs/', include('blogs.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/uBLOG/templates/base.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>uBLOG</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <header class="wrapper">
        <!-- <a href="{% url 'homepage' %}">Home</a> -->
        
        <!-- <a href="{% url 'blogs:blogs' %}">Blogs</a> -->
        <a href="{% url 'blogs:blogs' %}"><img class="logo" src="{% static 'logo.png' %}" alt="logo.png"></a>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li>
                        <form action="{% url 'accounts:logout' %}" class="logout-link" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li>
                        <a href="{% url 'blogs:create' %}" class="highlight">Create</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'accounts:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

backend/uBLOG/templates/homepage.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to uBLOG</h1>
{% endblock %}